### PR TITLE
Issue #2946725 by acbramley: Deny on empty setting not retained in up…

### PR DESCRIPTION
**Pull request by agentrickard**
See https://www.drupal.org/project/workbench_access/issues/2946725

This would need to go into the d.o. branch first, I think, so we can release the last alpha. However, this test is against the new code.

### CODE REVIEW

**Comment by jibran** [comment]
+1 to merge.

**Comment by agentrickard** [comment]
@jibran that isn't really a clear answer.

Yes, we should merge it to d.o. and release a new alpha?

Or, no, we should release as part of the major beta that's upcoming?

**Comment by jibran** [comment]
Sorry, I didn't know there was a question here and of course I haven't seen the d.o issue before posting above. 
IMO, this is a bug in last alpha release so I think we should fix it before the beta. Fixing it doesn't block us from releasing the beta so all good to merge.

**Comment by agentrickard** [comment]
I committed this via drupal.org and then merged up.

**Pull request closed without merging**
