### PR TITLE
Fixes https://www.drupal.org/node/2860372

### PR DESCRIPTION
**Pull request by larowlan**
See https://www.drupal.org/node/2860372

### CODE REVIEW

**Comment by agentrickard** [comment]
This is where we are going to add the AJAX submit?

**Comment by larowlan** [comment]
Yeah, ran out of time on Friday but still on my list

**Comment by agentrickard** [comment]
Changes to the manager class have outdated this PR. @larowlan

**Comment by larowlan** [comment]
No worries, this one is low priority @agentrickard

**Comment by agentrickard** [comment]
This is no longer relevant.

**Pull request closed without merging**
