### PR TITLE
Use new storage services on admin forms

### LINKED ISSUE #68: Fix admin forms for role and user sections
A couple of bugs introduced by splitting out the user and role storage:

On admin/config/workflow/workbench_access/sections/{section}/roles
```
Error: Call to undefined method Drupal\workbench_access\WorkbenchAccessManager::getPotentialRoles() in Drupal\workbench_access\Form\WorkbenchAccessByRoleForm->buildForm() (line 68 of modules/contrib/workbench_access/src/Form/WorkbenchAccessByRoleForm.php).
```

And we're missing returns in the WorkbenchAccessManager class on the wrappers to the other classes e.g
```
  /**
   * {@inheritdoc}
   *
   * @deprecated To be removed before 8.x-1.0 - use
   *   \Drupal\workbench_access\RoleSectionStorage::getRoles() instead
   */
  public function getRoles($id) {
    trigger_error(__CLASS__ . '::' . __METHOD__ . ' is deprecated, please use \Drupal\workbench_access\RoleSectionStorage::' . __METHOD__ . ' instead', E_USER_DEPRECATED);
    $this->roleSectionStorage->getRoles($id);
  }
```

### PR DESCRIPTION
**Pull request by acbramley**
Fixes #68

### CODE REVIEW

**Comment by larowlan** [comment]
:+1: from me, thanks @acbramley

**Comment by agentrickard** [comment]
Looks good. One major question:

* I know we're in Alpha, but doesn't this affect the current storage of section assignments in such a way that we have to provide an update for existing users?

We can address that in a follow-up, but I think it's a precondition of rolling a release.

**Comment by larowlan** [comment]
No, we're still storing it on the user field (user sections) and in the state system (role sections). We just split that responsibility out of the manager. This change moves to use those storage services direct, instead of via the deprecated methods on the manager.

**Comment by agentrickard** [comment]
Thanks!

**Comment by acbramley** [comment]
Thanks very much @agentrickard https://www.drupal.org/node/2868512 is the corresponding drupal ticket

**Pull request merged**
